# Generated by Django 4.2 on 2023-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tugilgan_yil', models.PositiveSmallIntegerField()),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
                ('tel_raqam', models.PositiveIntegerField()),
                ('faol', models.BooleanField(default=True)),
                ('longlitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('geolocation_url', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
